### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by henkth** [christiansteinert/tibetan-dictionary#1]
Dear Christian,

Thank you for the freely provided code for the tibetan dictionary. I am currently working on a Ladakhi-English dictionary with a friend. We would like to make an app that contains rudimentary styles like bold and italics. Since your dictionary needs a csv dictionary file, it contains no styles. Do you think this can be implemented in your current code or do I have to look elsewhere?

Thanks a lot,

Henk Thoma

**Comment by christian-steinert-itaricon** [comment]
Dear Henk

Sorry for replying so late. I had not noticed your ticket and I am very sorry about it.
I don't know if my reply is still of any use for this but using my app as a basis might be an option. 

It is true that my app contains no formatting in the source data but already now there are some replacement rules which actually do add highlighting in a few cases before everything is displayed. These rules are part of the dictionary definition. Within these there are a few replacement rules based on regular expressions.

Alternatively, you could simply add HTML code into the dictionary data and then remove some escaping from the frontend code so that your HTML is added into the result pages. In this case you would of course have to make sure that your data does not contain any unescaped < > & characters except for the actual HTML code but but if this is an option then very few code changes should be necessary to get rid of the escaping rules so that the HTML code would come through unfitered.

Another option would be to add your own formatting rules and then convert these into HTML. This should require little effort as well.

If you still have questions, feel free to reply. Once again, sorry for replying so late.
Christian

**Comment by henkth** [comment]
Dear Christian,

Thank you for your reply. In case I have some questions, will definitely contact you.

Cheers,

Henk
