### ISSUE TITLE
hyperlink missing: རྣམ་གཡེང་

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#29]
Hopkins comment 1992 says: "See རྣམ་པར་གཡེང་པ་
this lacks the hyperlink underline function, but in any case it should link to the listing you do have, རྣམ་པར་གཡེང་བ་
You do have that correct hyperlink in the Ranjung Yeshe definition.

**Comment by christiansteinert** [comment]
The application can only link to the same term that is written. It will find and hyperlink things only if the spelling is completely identical and there is no way to override this it add any manual links on top of this behavior. For this reason tere is no way to link to the entry that ends with ...བ་  if the definition spells it with ...པ་

I guess the only option would be to correct the Hopkins entry since the reference there seems to be misspelled. I think that's what I'll do.

**Comment by christiansteinert** [comment]
The Hopkins entry is now fixed. The online database will be fixed soon for this entry.
