### ISSUE TITLE
Negi typos

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#32]
སྟོང་ཉིད་སྙིང་རྗེ་དབྱེར་མེད་པ་
vi. śūnyatākadyaṇābhinnam should be, as it is in the example just below in the same definition, (vi.) śūnyatākaruṇābhinnaṃ

śūnyatākadyaṇābhinnam doesn't exist in Sanskrit

**Comment by jfhartzell** [comment]
མདོ་སྡེ་པ་
Tsepak Ridgzin has "sautrātitika School" instead of "sautrāntika School". There's no Sanskrit word "sautrātitika"

**Comment by christiansteinert** [comment]
Dear James,

Sincere apology for the extreme delay of addressing your report. I have now fixed the data files and with the next database update these problems will also fixed in the dictionary. 

I greatly appreciate reports like this even though for various reasons it has taken me a really long time to address your report.

**Comment by jfhartzell** [comment]
Hi Christian
Totally awesome to have your dicitionary and be able to use it. Understand completely that sometimes it takes a long time to get around to certain things!

**Comment by jfhartzell** [comment]
Hi Christian
I think I found another one: under སྔོན་ in Negi, there's an "avya." abbreviation under definition 2 that doesn't show a hyper link to a clarification in any of the browsers I have.

**Comment by jfhartzell** [comment]
Negi: another one, under "རྒྱས་པ་", 2nd bullet, "saṃ" has no hyperlink clarification
